export const ErrorCode = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  RATE_LIMITED: "RATE_LIMITED",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
  RESOURCE_ARCHIVED: "RESOURCE_ARCHIVED",
  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
